#!/bin/bash

load inquirer

check() {
  if [ "$DEBUG" = "true" ]; then
    log::info "[DEBUG][service][workspace]: $SERVICE_CONFIG"
    cat $SERVICE_CONFIG
  fi

  config::check_or_set SERVICE_WORKSPACE_COMPANY text $SERVICE_CONFIG
  # config::check_or_set SERVICE_REMOTEDEV_SOURCE_CODE_DIR text $SERVICE_CONFIG
  config::check_or_set SERVICE_WORKSPACE_INLETS_CLIENT_ID text $SERVICE_CONFIG "Input Inlets Client ID:"
  config::check_or_set SERVICE_WORKSPACE_INLETS_CLIENT_SECRET text $SERVICE_CONFIG "Input Inlets Client Secret:"
  config::check_or_set SERVICE_WORKSPACE_INLETS_PORT text $SERVICE_CONFIG "Input Inlets Port:"
  config::check_or_set SERVICE_WORKSPACE_SOURCE_CODE_DIR text $SERVICE_CONFIG "Input Source Code Dir:"
  config::check_or_set SERVICE_WORKSPACE_GIT_USER text $SERVICE_CONFIG "Input Git User:"
  config::check_or_set SERVICE_WORKSPACE_GIT_EMAIL text $SERVICE_CONFIG "Input Git Email:"
  config::check_or_set SERVICE_WORKSPACE_SSH_PORT text $SERVICE_CONFIG "Input SSH Port:"
  config::check_or_set SERVICE_WORKSPACE_PREVILEGED yesno $SERVICE_CONFIG "Allow Previledge ?"
  config::check_or_set SERVICE_WORKSPACE_SSH_CONFIG text $SERVICE_CONFIG "Input SSH Config Dir:"
}

check $@
