version: '3.7'

services:
  workspace:
    restart: always
    image: whatwewant/workspace:${SERVICE_WORKSPACE_IMAGE_VERSION}
    ports:
      - 0.0.0.0:${SERVICE_WORKSPACE_SSH_PORT}:22
    hostname: ${SERVICE_WORKSPACE_COMPANY}
    privileged: ${SERVICE_WORKSPACE_PREVILEGED:-true}
    environment:
      INLETS_CLIENT_ID: ${SERVICE_WORKSPACE_INLETS_CLIENT_ID}
      INLETS_CLIENT_SECRET: ${SERVICE_WORKSPACE_INLETS_CLIENT_SECRET}
      INLETS_PORT: ${SERVICE_WORKSPACE_INLETS_PORT}
      GIT_USER: ${SERVICE_WORKSPACE_GIT_USER}
      GIT_EMAIL: ${SERVICE_WORKSPACE_GIT_EMAIL}
    volumes:
      - ${SERVICE_DATA}/.vscode-server:/home/workspace/.vscode-server
      - ${SERVICE_WORKSPACE_SSH_CONFIG}:/home/workspace/.ssh
      - ${SERVICE_DATA}/.gpm:/home/workspace/.gpm
      - ${SERVICE_WORKSPACE_SOURCE_CODE_DIR}:/home/workspace/code
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

networks:
  default:
    external: true
    name: compose-ingress
