version: '3.7'

services:
  workspace:
    restart: always
    image: whatwewant/workspace:${SERVICE_WORKSPACE_IMAGE_VERSION}
    ports:
      - 0.0.0.0:${SERVICE_WORKSPACE_SSH_PORT}:22
      - 0.0.0.0:${SERVICE_WORKSPACE_HTTP_SERVER_PORT}:80
      - 0.0.0.0:${SERVICE_WORKSPACE_VSCODE_SERVER_PORT}:${SERVICE_WORKSPACE_VSCODE_SERVER_PORT}
    hostname: ${SERVICE_WORKSPACE_COMPANY}
    privileged: ${SERVICE_WORKSPACE_PREVILEGED:-true}
    environment:
      INLETS_CLIENT_ID: ${SERVICE_WORKSPACE_INLETS_CLIENT_ID}
      INLETS_CLIENT_SECRET: ${SERVICE_WORKSPACE_INLETS_CLIENT_SECRET}
      INLETS_PORT: ${SERVICE_WORKSPACE_INLETS_PORT}
      GIT_USER: ${SERVICE_WORKSPACE_GIT_USER}
      GIT_EMAIL: ${SERVICE_WORKSPACE_GIT_EMAIL}
      HTTP_SERVER_PORT: ${SERVICE_WORKSPACE_HTTP_SERVER_PORT}
      VSCODE_SERVER_PORT: ${SERVICE_WORKSPACE_VSCODE_SERVER_PORT}
    volumes:
      - ${SERVICE_WORKSPACE_VSCODE_CONFIG}:/home/workspace/.vscode-server
      - ${SERVICE_WORKSPACE_SSH_CONFIG}:/home/workspace/.ssh
      - ${SERVICE_WORKSPACE_GPM_CONFIG}:/home/workspace/.gpm
      - ${SERVICE_WORKSPACE_SOURCE_CODE_DIR}:/home/workspace/code
      # - ${SERVICE_DATA}/zmicro/data:/data
      # - ${SERVICE_DATA}/zmicro/configs:/configs
      - ${SERVOCE_WORKSPACE_ZMICRO_DATA}:/zmicro_data
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

networks:
  default:
    external: true
    name: compose-ingress
